{"name": "test_access_control[-401]", "status": "broken", "statusDetails": {"message": "NameError: name 'api' is not defined", "trace": "user = '', status_code = 401\n\n    @pytest.mark.parametrize(\n        (\"user\", \"status_code\"),\n        [\n            (\"admin\", 200),\n            (\"guest\", 403),\n            (\"\", 401)\n        ]\n    )\n    def test_access_control(user, status_code):\n>       response = api.login(user)\nE       NameError: name 'api' is not defined\n\ntests\\test_api.py:12: NameError"}, "parameters": [{"name": "user", "value": "''"}, {"name": "status_code", "value": "401"}], "start": 1748006179022, "stop": 1748006179022, "uuid": "ef83e737-8110-438a-b894-c04fc47f948b", "historyId": "f4ecb25f6bdf0b3ed4d568285934d486", "testCaseId": "156d2972e5a87051ba43e2b010fc8290", "fullName": "tests.test_api#test_access_control", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "LAPTOP-S7QL1I5I"}, {"name": "thread", "value": "18660-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}